### ISSUE TITLE
pipo.onseg temp mod only works when @duration == 1

### ISSUE THREAD

**Issue by josephlarralde** [Ircam-RnD/pipo#4]
Reported from svn : 

_By Diemo Schwarz, juin  1, 2017:_
it should be possible to request mean, std, etc. without calculating duration

_By Diemo Schwarz, nov. 16, 2017:_
in the current code, there are 2 cases:
1. when duration is off, onsets markers are reported immediately (good for realtime)
2. when duration is on, onsets with duration and temp.mod values are reported at the beginning of the next segment.
TODO: when any temp.mod or duration is enabled, switch to 2.

**Comment by diemoschwarz** [comment]
fixed with rc23f89c
